{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.persistence.config.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  {{- if not (eq .Values.persistence.config.storageClass "~") }}
  storageClassName: "{{ .Values.persistence.config.storageClass }}"
  {{- end }}
{{- end }}