{{- if or .Values.enableDLNA .Values.enableLocalDiscovery }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}-local-discovery
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  {{- if .Values.discoveryService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.discoveryService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    {{- if .Values.enableLocalDiscovery }}
    - port: 7359
      targetPort: local-discovery
      name: local-discovery
    {{- end }}
    {{- if .Values.enableDLNA }}
    - port: 1900
      targetPort: dlna
      name: dlna
    {{- end }}
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
{{- end }}