{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-media
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.persistence.media.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if not (eq .Values.persistence.media.storageClass "~") }}
  storageClassName: "{{ .Values.persistence.media.storageClass }}"
  {{- end }}
{{- end }}