kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "radarr.fullname" . }}-data
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if not (eq .Values.persistence.storageClass "~") }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}