## @section General settings

## @param replicaCount Replica count
replicaCount: 1

## @param image.repository The Docker image to use
## @param image.pullPolicy Pull policy
## @param image.tag Image tag. Defaults to Chart version
image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

## @param imagePullSecrets
## @param nameOverride
## @param fullnameOverride
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## @param resources Set resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## @param nodeSelector 
nodeSelector: {}

## @param tolerations
tolerations: []

## @param affinity
affinity: {}

## @param podAnnotations
podAnnotations: {}

## @param podSecurityContext
podSecurityContext: {}
  # fsGroup: 2000

## @param securityContext
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## @param service.type Service type
## @param service.port Service port
## @param service.annotations Additional service annotations
## @param service.labels Additional service labels
## @param service.clusterIP Specify explicit cluster IP
## @param service.loadBalancerIP Specify explicit load balancer IP
## @param service.loadBalancerSourceRanges Specify load balancer source range
## @param service.externalIPs Specify external IP
## @param service.externalTrafficPolicy External traffic policy
service:
  type: ClusterIP
  port: 8096
  annotations: {}
  labels: {}
  clusterIP:
  loadBalancerIP:
  loadBalancerSourceRanges: []
  externalIPs: []
  externalTrafficPolicy: Cluster

## @section Discovery Service

## @param enableDLNA Enables DLNA port. Creates a loadbalancer service
## @param enableLocalDiscovery Enables local discovery port. Creates a loadbalancer service
enableDLNA: false
enableLocalDiscovery: false

## @param discoveryService.annotations Annotations for the discovery service
## @param discoveryService.labels Labels for the discovery service
## @param discoveryService.loadBalancerIP Specify loadbalancer IP
## @param discoveryService.loadBalancerSourceRanges Specify loadbalancer source range
discoveryService:
  annotations: {}
  labels: {}
  loadBalancerIP:
  loadBalancerSourceRanges: []

## @section Ingress

## @param ingress.enabled Enable ingress
## @param ingress.className Ingress class name
## @param ingress.annotations Ingress annotations
## @param ingress.hosts [array] Hosts of the ingress record
## @param ingress.tls [array] List of secrets with the TLS certificate
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## @section Persistence

## @param persistence.config.enabled Enable persistence for the config
## @param persistence.config.storageClass Choose storage class for the PVC. "~" will choose the default storage provider
## @param persistence.config.existingClaim Specify an existing claim
## @param persistence.config.accessModes Access modes of the PVC
## @param persistence.config.size Size of the PVC
persistence:
  config:
    enabled: false
    storageClass: "~"
    existingClaim:
    accessModes: 
      - ReadWriteOnce
    size: 1Gi
## @param persistence.media.enabled Enable persistence for the config
## @param persistence.media.storageClass Choose storage class for the PVC. "~" will choose the default storage provider
## @param persistence.media.existingClaim Specify an existing claim
## @param persistence.media.accessModes Access modes of the PVC
## @param persistence.media.size Size of the PVC
  media:
    enabled: false
    storageClass: "~"
    existingClaim:
    accessModes: 
      - ReadWriteOnce
    size: 10Gi

## @param extraVolumes Specify extra volumes
extraVolumes: []
  #- name: renderD129
  #  hostPath:
  #    path: /dev/dri/renderD129

## @param extraVolumeMounts Specify extra volume mounts
extraVolumeMounts: []
  #- mountPath: /dev/dri/renderD129
  #  name: renderD129